executors.yml
https://github.com/ClouDesire/support/issues/4329
=> Add Docker Authenticated Pulls

.circleci/config.yml
ref https://github.com/ClouDesire/support/issues/4336
=> [semver:patch] fix publishing issues - 0.1.1

src/commands/test_sonar.yml, src/scripts/sonar.sh, src/scripts/sonar_get_server_version.sh
ref https://github.com/ClouDesire/support/issues/4459
=> [semver:patch] Improve sonar command

src/commands/maven_with_cache.yml
resolve https://github.com/ClouDesire/circleci-orbs/issues/7
=> [semver:skip] Add configurable maven settings path

.circleci/config.yml, src/commands/cookbooks_setup.yml, src/commands/git_checkout.yml, src/jobs/cookbooks_build.yml, src/jobs/cookbooks_test.yml, src/scripts/git_checkout.sh, src/tests/download_repo.bats
Add the GIT_EMAIL and GIT_USERNAME parameters to set git global config for username and email. 
Also adds the MERGE_MASTER parameter (true by default). When this is true, the master branch is merged with the current CIRCLE_BRANCH.
=> [semver:skip] Add more parameters to git_checkout

CHANGELOG.md, src/commands/circleci_trigger_pipeline.yml, src/scripts/circleci_trigger_pipeline.sh, src/scripts/git_setup.sh
- Add step to trigger a CircleCI pipeline [`#34`](https://github.com/ClouDesire/circleci-orbs/pull/34)
- Add 'maven_install_library' command [`#29`](https://github.com/ClouDesire/circleci-orbs/pull/29)
- Add 'git_checkout' command [`#27`](https://github.com/ClouDesire/circleci-orbs/pull/27)
- add configurable maven settings path [`#30`](https://github.com/ClouDesire/circleci-orbs/pull/30)
resolve #35
=> [semver:minor] Release v0.1.0

src/scripts/git_checkout.sh
=> [semver:skip] fix issue with REPO_NAME

src/commands/maven_install_library.yml, src/scripts/maven_install_library.sh
=> [semver:skip] Fix maven_install_library command

CHANGELOG.md
=> [semver:patch] Release v0.1.1

src/commands/maven_with_cache.yml
=> [semver:skip] remove use of settings_file in one step

src/scripts/sonar.sh
resolve https://github.com/ClouDesire/circleci-orbs/issues/52
=> [semver:patch] fix sonar step when mvn is installed but not used

src/commands/test_sonar.yml, src/scripts/sonar.sh
https://github.com/ClouDesire/support/issues/4606
=> [semver:patch] Pin sonar version

src/tests/github_pr_read_labels.bats
=> [semver:patch] fix bats test execution

src/commands/cookbooks_kitchen_test.yml, src/jobs/cookbooks_test.yml, src/scripts/cookbooks_test.sh
ref https://github.com/ClouDesire/support/issues/4313
=> [semver:minor] Add repeatable kitchen suites

src/commands/git_checkout.yml, src/commands/maven_with_cache.yml, src/scripts/git_checkout.sh
Build started failing due to missing settings.xml in the correct place
=> [semver:patch] Git checkout fix on home folder by default

src/executors/docker_java.yml
close https://github.com/ClouDesire/circleci-orbs/issues/65
=> [semver:minor] Add Java generic executor

src/tests/github_pr_read_labels.bats
close https://github.com/ClouDesire/circleci-orbs/issues/64
=> [semver:skip] fix bats tests on master

src/commands/maven_with_cache.yml
ref https://github.com/ClouDesire/support/issues/4789
=> [semver:patch] incremental keys for maven cache

src/scripts/git_checkout.sh, src/tests/download_repo.bats
ref https://github.com/ClouDesire/support/issues/4860
=> [semver:patch] fix issue with git authentication

src/commands/docker_run_and_test.yml
ref https://github.com/ClouDesire/support/issues/4747
=> [semver:minor] Add command to run and test docker container

src/commands/maven_with_cache.yml
ref https://github.com/ClouDesire/support/issues/4869
=> [semver:patch] Add cache_key to invalidate m2 cache

src/commands/docker_run_and_test.yml, src/scripts/docker_run.sh, src/scripts/utility_check_url.sh
ref https://github.com/ClouDesire/support/issues/4747
=> [semver:patch] Docker run and test commands refactor

.circleci/config.yml, src/@orb.yml
ref https://github.com/ClouDesire/support/issues/4846
The issue is probably the button with the URL to the PR when the step is run on branch master.
=> [semver:patch] Fix Slack notification

src/scripts/maven_release.sh
ref https://github.com/ClouDesire/support/issues/4745
=> [semver:patch] edit maven release message

README.md, src/commands/maven_install_library.yml, src/scripts/maven_install_library.sh
=> [semver:patch] Fix Java 11 Build

src/scripts/utility_check_url.sh
ref https://github.com/ClouDesire/support/issues/4906
=> [semver:patch] add check on the HTTP_CODE returned by the curl

src/commands/maven_with_cache.yml
https://app.circleci.com/pipelines/github/ClouDesire/java-api-client/559/workflows/ad3ea440-2bf6-4333-85be-fbebc90f85f3/jobs/2571/parallel-runs/0/steps/0-105
=> [semver:patch] Fix cache restore on branches

src/jobs/maven_release.yml, src/scripts/maven_release.sh
ref https://github.com/ClouDesire/support/issues/4926
=> [semver:patch] Add tag creation on maven release

src/commands/maven_install_library.yml, src/scripts/git_checkout.sh, src/scripts/maven_install_library.sh, src/tests/download_repo.bats
ref https://github.com/ClouDesire/support/issues/4944
=> [semver:patch] Remove circleci-agent step halt

src/commands/maven_install_library.yml
ref https://github.com/ClouDesire/support/issues/4944
=> [semver:patch] Fix maven_install_library issue

src/commands/cookbooks_setup.yml, src/jobs/cookbooks_build.yml, src/scripts/cookbooks_build.sh
ref https://github.com/ClouDesire/support/issues/4972
=> [semver:patch] Change ssh_key name used in cookbooks_build

src/scripts/cookbooks_build.sh, src/scripts/cookbooks_cleanup.sh, src/scripts/cookbooks_test.sh
ref https://github.com/ClouDesire/support/issues/4972
=> [semver:patch] Fix kitchen ssh key default path

src/jobs/yarn_release.yml, src/scripts/yarn_release.sh
ref https://github.com/ClouDesire/support/issues/4824
=> [semver:minor] Add support for yarn release

src/executors/chefdk.yml
ref https://github.com/ClouDesire/support/issues/5091
=> [semver:patch] add KITCHEN_LOG_OVERWRITE

src/executors/chefdk.yml
ref https://github.com/ClouDesire/support/issues/5091
=> [semver:patch] set KITCHEN_LOG_OVERWRITE as string

src/commands/docker_run_and_test.yml, src/scripts/docker_run.sh
https://github.com/ClouDesire/syndication-api/pull/41/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R34
=> [semver:minor] Support image name and version parameter in docker run and test

src/scripts/sonar.sh
ref https://github.com/ClouDesire/support/issues/5166
=> [semver:patch] test_sonar fails if not on PR or master

README.md
ref https://github.com/ClouDesire/support/issues/5190
=> add information for github_pr_read_labels step

src/executors/docker_java_postgres.yml
ref https://github.com/ClouDesire/support/issues/5173
=> upgrade postgres image version to 13.3-alpine

src/scripts/git_checkout.sh, src/scripts/git_merge_default.sh, src/tests/download_repo.bats
ref https://github.com/ClouDesire/support/issues/5248
=> [semver:minor] Allow different default_branch then main or master

src/commands/git_checkout.yml, src/commands/git_merge_default.yml, src/commands/github_pr_add_comment.yml, src/commands/github_pr_read_labels.yml, src/scripts/git_checkout.sh, src/scripts/git_merge_default.sh, src/scripts/github_pr_add_comment.sh, src/scripts/github_pr_read_labels.sh, src/scripts/setup.sh
ref https://github.com/ClouDesire/support/issues/5288
=> [semver:patch] Fix issue when `jq` is not on the executor

README.md, src/commands/create_ssh_tunnel.yml
ref https://github.com/ClouDesire/support/issues/5479
=> [semver:minor] Add `create_ssh_tunnel` command

src/commands/bundler_restore_cache.yml, src/commands/bundler_save_cache.yml
https://app.circleci.com/pipelines/github/ClouDesire/ops/7021/workflows/63bbd14d-a013-4a34-888d-a74906e3494b/jobs/19226
=> [semver:patch] Override bundler cache name

src/scripts/git_checkout.sh
```
From https://github.com/ClouDesire/ci-conf
* branch            HEAD       -> FETCH_HEAD
merge: origin/ - not something we can merge
```
=> [semver:patch] Fix broken automerge in git checkout

src/scripts/sonar.sh, src/tests/github_pr_add_comment.bats
fixes https://github.com/ClouDesire/circleci-orbs/issues/121
=> [semver:patch] Fix sonar on tagged builds

src/jobs/cookbooks_build.yml, src/jobs/cookbooks_test.yml
ref https://github.com/ClouDesire/support/issues/5889
=> [semver:minor] Set chef_workstation as default executor chef cookbooks jobs

src/commands/test_sonar.yml, src/scripts/sonar.sh
ref https://github.com/ClouDesire/support/issues/5892
=> [semver:minor] Set maven sonarscanner plugin default version to latest

src/scripts/cookbooks_build.sh
ref https://github.com/ClouDesire/support/issues/5889
=> [semver:minor] Use chef-workstation in cookbook-build script

.circleci/config.yml, src/jobs/cookbooks_build.yml, src/jobs/cookbooks_test.yml
ref https://github.com/ClouDesire/support/issues/6046
=> [semver:minor] Add `executor_resource_class` to cookbook jobs

src/scripts/sonar.sh
=> support both CIRCLE_PULL_REQUEST and CI_PULL_REQUEST

src/commands/cookbooks_kitchen_test.yml, src/jobs/cookbooks_test.yml, src/scripts/cookbooks_cleanup.sh, src/scripts/cookbooks_test.sh
ref https://github.com/ClouDesire/support/issues/6308
=> [semver:MAJOR] Run a converge against only CONCURRENCY value instances

.circleci/config.yml, src/commands/test_sonar.yml, src/scripts/sonar.sh
ref https://github.com/ClouDesire/support/issues/6025
=> [semver:major] Add support for SonarCloud

.circleci/config.yml, src/commands/maven_aggregate_tests_results.yml
ref https://github.com/ClouDesire/support/issues/7184
=> [semver:patch] update tests results path

src/jobs/maven_release.yml
ref https://github.com/ClouDesire/support/issues/7420
=> [semver:patch] Fix maven_release job

src/commands/maven_aggregate_tests_results.yml
**SEMVER Update Type:**
Fix test reporting when flaky/reruns are present
=> [semver:minor] Fix flaky/rerun test reporting

src/executors/docker_java.yml
ref https://github.com/ClouDesire/support/issues/7650
=> [semver:minor] update default `java_version` for the java executor to `17.0.9`

src/commands/maven_aggregate_tests_results.yml
**SEMVER Update Type:**
**Closes Issues:**
-  ISSUE URL
=> fix: maven test error rerun reporting

src/scripts/yarn_release.sh
ref https://app.circleci.com/pipelines/github/ClouDesire/angular-cloudesire-common/697/workflows/dc8287b6-f35d-42c1-a973-9fd5cb592b79/jobs/1264/parallel-runs/0/steps/0-106
=> fix: change `.npmrc` setup in `yarn_release` script
